# Generated by Django 5.2 on 2025-04-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
